apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falkordb-browser.fullname" . }}
  labels:
    {{- include "falkordb-browser.labels" . | nindent 4 }}
{{ include "falkordb-browser.validateEncryptionKeySecret" . }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.env.nextauthSecret | quote }}
  {{- if not .Values.encryption.existingSecret.name }}
  ENCRYPTION_KEY: {{ include "falkordb-browser.encryptionKey" . | quote }}
  {{- end }}
