import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs";
import { getCsvTempDir } from "@/app/lib/csv-storage-local";
import { getCsvStorageProvider } from "@/app/lib/csv-storage";
import { getClient } from "@/app/api/auth/[...nextauth]/options";
import { getCorsHeaders } from "@/app/api/utils";

// UUID v4 pattern — all tempIds are UUIDs generated by the upload endpoint.
const UUID_PATTERN =
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Serve a temporarily uploaded CSV file for use with FalkorDB's `LOAD CSV`.
 *
 * No authentication is required — the UUID-based tempId acts as an
 * unguessable one-time token.  The file is deleted by the load-csv execute
 * endpoint after the Cypher query finishes, regardless of outcome.
 */
export async function GET(
    _request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    const { id } = await params;

    if (!UUID_PATTERN.test(id)) {
        return new NextResponse("Not found.", { status: 404 });
    }

    const dir = getCsvTempDir();
    const filePath = path.join(dir, `${id}.csv`);

    // Path-traversal guard — ensure the resolved path stays inside csv-temp/.
    const resolved = path.resolve(filePath);
    const resolvedDir = path.resolve(dir);
    if (!resolved.startsWith(resolvedDir + path.sep)) {
        return new NextResponse("Not found.", { status: 404 });
    }

    let content: Buffer;
    try {
        content = await fs.promises.readFile(resolved);
    } catch {
        return new NextResponse("Not found.", { status: 404 });
    }

    return new NextResponse(content as unknown as BodyInit, {
        status: 200,
        headers: {
            "Content-Type": "text/csv; charset=utf-8",
            "Content-Disposition": `inline; filename="${id}.csv"`,
            // Prevent caching — the file will be deleted after use.
            "Cache-Control": "no-store",
        },
    });
}

/**
 * Best-effort delete for temp CSV files when a user cancels/closes the upload
 * flow after the file has already been uploaded.
 */
export async function DELETE(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    const session = await getClient(request);
    if (session instanceof NextResponse) return session;

    const { id } = await params;

    if (!UUID_PATTERN.test(id)) {
        return NextResponse.json(
            { message: "Invalid key." },
            { status: 400, headers: getCorsHeaders(request) }
        );
    }

    await getCsvStorageProvider().delete(id);

    return new NextResponse(null, {
        status: 204,
        headers: getCorsHeaders(request),
    });
}
